# Generated by Django 2.0.4 on 2018-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('b', 'Bouquet'), ('p', 'Present'), ('c', 'Composition')], default='b', max_length=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
