# Generated by Django 2.0.4 on 2018-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180422_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_1',
            field=models.ImageField(upload_to='shop/static/img/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_2',
            field=models.ImageField(default=None, upload_to='shop/static/img/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_3',
            field=models.ImageField(default=None, upload_to='shop/static/img/products'),
        ),
    ]
