# Generated by Django 2.0.4 on 2018-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180423_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_1',
            field=models.ImageField(upload_to='shop/static/img/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_2',
            field=models.ImageField(upload_to='shop/static/img/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_3',
            field=models.ImageField(upload_to='shop/static/img/products'),
        ),
    ]
