# Generated by Django 2.0.4 on 2018-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180424_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('n', 'item_new'), ('h', 'item_hit'), ('a', 'item_action'), (' ', '')], default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_1',
            field=models.ImageField(upload_to='products/img'),
        ),
    ]
