# Generated by Django 2.0.4 on 2018-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180425_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('item_new', 'n'), ('item_hit', 'h'), ('item_action', 'a'), (' ', '')], default=' ', max_length=10),
        ),
    ]
