# Generated by Django 2.0.4 on 2018-04-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180425_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bouquet', 'Bouquet'), ('present', 'Present'), ('composition', 'Composition')], default='b', max_length=1),
        ),
    ]
